with-expecter: True
disable-version-string: True
all: True
recursive: true
packages:
  github.com/goravel/framework/contracts:
    config:
      dir: mocks/{{replaceAll .InterfaceDirRelative "contracts" ""}}
      filename: "{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"
