name: Test
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'filesystem/**'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
  AWS_URL: ${{ secrets.AWS_URL }}
  ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
  ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
  ALIYUN_BUCKET: ${{ secrets.ALIYUN_BUCKET }}
  ALIYUN_URL: ${{ secrets.ALIYUN_URL }}
  ALIYUN_ENDPOINT: ${{ secrets.ALIYUN_ENDPOINT }}
  TENCENT_ACCESS_KEY_ID: ${{ secrets.TENCENT_ACCESS_KEY_ID }}
  TENCENT_ACCESS_KEY_SECRET: ${{ secrets.TENCENT_ACCESS_KEY_SECRET }}
  TENCENT_BUCKET: ${{ secrets.TENCENT_BUCKET }}
  TENCENT_URL: ${{ secrets.TENCENT_URL }}
  MINIO_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
  MINIO_ACCESS_KEY_SECRET: ${{ secrets.MINIO_ACCESS_KEY_SECRET }}
  MINIO_BUCKET: ${{ secrets.MINIO_BUCKET }}
  MINIO_URL: ${{ secrets.MINIO_URL }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
jobs:
  filesystem:
    strategy:
      matrix:
        go: [ '1.18' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./filesystem/...