name: Mockery
on:
  pull_request:
jobs:
  mockery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Mockery
        run: |
          docker pull vektra/mockery:v2.42.1
      - name: Generate Mocks
        run: |
          docker run -v "$PWD":/src -w /src vektra/mockery:v2.42.1
      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit changes
        with:
          commit_message: "chore: update mocks"
