name: Welcome
on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          FIRST_PR: |
            Hi @{{ author }} 👋
            
            Thanks for opening this PR to Goravel, we will review it as soon as possible! 💖
            感谢您向 Goravel 提交此 PR，我们将尽快 Review！ 💖

          FIRST_PR_MERGED: |
            Hi @{{ author }} 🎉
            
            Congrats on merging your first PR! Goravel will better because of you! 💖
            恭喜您的第一个 PR 被合并，Goravel 因您而更好！ 💖
